# Generated by Django 2.1.2 on 2018-10-30 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnderlyingSecurityIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_id', models.PositiveIntegerField(help_text='Underlying security ID')),
                ('weight', models.FloatField(help_text='Underlying security weight')),
            ],
        ),
        migrations.CreateModel(
            name='UnderlyingSecurityIngestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True, help_text='Date and time of ingestion')),
                ('date', models.DateField(help_text='Synthetic index date')),
                ('synthetic_index', models.FloatField(help_text='Synthetic index on a specific date')),
                ('calculated_on', models.DateTimeField(auto_now=True, help_text='Date and time of synthetic index calculation')),
            ],
        ),
        migrations.CreateModel(
            name='UnderlyingSecurityValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(help_text='Underlying security price')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexes.UnderlyingSecurityIndex')),
                ('ingestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexes.UnderlyingSecurityIngestion')),
            ],
        ),
    ]
